services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    # for api keys
    env_file:
      - ./.env

  web:
    build: ./web
    ports:
      - "8080:8080"
    environment:
    - SERVER_URL=http://localhost:5000
